[settings]
jobs = 1

[tools]
markdownlint-cli2 = "0.22.1"
node = "25.9.0"
pipx = "1.15.0"
"pipx:poetry" = "2.3.2"
python = "3.14"

[env]
_.python.venv = { path = ".venv", create = true }

[tasks.p]
run = "poetry"

[tasks.install]
run = """
pip install poetry
poetry install
"""

[tasks.update]
run = """
mise upgrade
pip install -U pip
poetry update
poetry show -o
"""
